services:
  app:
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    container_name: arcg-prod
    ports:
      - '3000:3000'
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
    networks:
      - arcg-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '--quiet', '--tries=1', '--spider', 'http://localhost:3000/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  arcg-network:
    driver: bridge
