services:
  test:
    build:
      context: .
      target: test
      dockerfile: Dockerfile
    container_name: arcg-test
    environment:
      - CI=true
      - NODE_ENV=test
    volumes:
      - ./coverage:/app/coverage
    networks:
      - arcg-test-network

networks:
  arcg-test-network:
    driver: bridge
